import { registerHitlField } from "./registry";
import { MarkdownField } from "./MarkdownField";
import { TextField } from "./TextField";
import { TextareaField } from "./TextareaField";
import { NumberField } from "./NumberField";
import { SelectField } from "./SelectField";
import { MultiSelectField } from "./MultiSelectField";
import { RadioField } from "./RadioField";
import { CheckboxField } from "./CheckboxField";
import { SwitchField } from "./SwitchField";
import { DateField } from "./DateField";
import { ButtonGroupField } from "./ButtonGroupField";
import { DividerField } from "./DividerField";
import { HeadingField } from "./HeadingField";
import "./custom";

registerHitlField("markdown", MarkdownField);
registerHitlField("text", TextField);
registerHitlField("textarea", TextareaField);
registerHitlField("number", NumberField);
registerHitlField("select", SelectField);
registerHitlField("multiselect", MultiSelectField);
registerHitlField("radio", RadioField);
registerHitlField("checkbox", CheckboxField);
registerHitlField("switch", SwitchField);
registerHitlField("date", DateField);
registerHitlField("button_group", ButtonGroupField);
registerHitlField("divider", DividerField);
registerHitlField("heading", HeadingField);
